package proto

var (
	ERR_CENTER_INVALID_JSON     = 1
	ERR_CENTER_INVALID_JSON_TXT = "错误的json格式"

	ERR_CENTER_INVALID_ID     = 2
	ERR_CENTER_INVALID_ID_TXT = "服务器ID不存在"

	ERR_CENTER_INVALID_PASSWD     = 3
	ERR_CENTER_INVALID_PASSWD_TXT = "服务器密码不正确"
)
